#!/bin/bash   
#   
# memcached:    MemCached Daemon   
#   
### BEGIN INIT INFO
# Provides:			memcached
# Required-Start:		$local_fs $remote_fs $network 
# Should-Start:			memcached
# Should-Stop:			memcached
# Required-Stop:		$local_fs $remote_fs $network
# Default-Start:		3 5
# Default-Stop:			0 1 2 6
# Short-Description:		Memcached-replication
# Description:			Start the memcached daemon
### END INIT INFO
# chkconfig:    - 90 25    
# description:  MemCached Daemon   
#   
# Source function library.   

#. /etc/rc.status
    
start()    
{   
        echo -n "Starting memcached: "  
        if [ $SERVER_INFO == "slave" ];then
        else

        fi
        echo   
}   
    
stop()    
{   
        echo -n "Shutting down memcached: "  
        killproc memcached    
        echo   
}   
    
[ -f /usr/local/memcached/bin/memcached ] || exit 0  
    
# See how we were called.   
case "$1" in   
  start)   
        start   
        ;;   
  stop)   
        stop   
        ;;   
  restart|reload)   
        stop   
        start   
        ;;   
  *)   
        echo "Usage: $0 {start|stop|restart|reload}"  
        exit 1  
esac   
exit 0  
